import Foundation

/// Shared by supported extractors. This is semantic guidance, not sender/brand exclusions.
enum TaskReviewPolicy {
    static let instructions = """
    Evaluate whether a useful, concrete responsibility remains outstanding at REVIEW TIME, not merely whether the source once contained an imperative. Read supplied later observations in the same conversation for explicit answers, completion, cancellation, superseding requests or an expired opportunity. Those later observations may invalidate or clarify the original obligation; they cannot be the sole evidence for creating a different task from this source. Preserve unresolved obligations when later evidence is inconclusive. A passed deadline by itself does not mean a responsibility was completed or no longer owed.
    Access material is not a standalone responsibility: issuing a one-time sign-in code, authentication link, verification token or temporary pass does not itself require a persistent task. Never copy credentials or codes into task text. Preserve a separately stated substantive obligation, such as completing required paperwork; opening a portal or logging in is usually a means to that outcome, not a second obligation.
    Distinguish required or personally accepted work from optional engagement. Optional surveys, reviews, feedback invitations, promotional offers, broad encouragement and rhetorical questions do not create owed work merely because they ask the reader to act. A personally assigned substantive response can still be an obligation; sender identity alone decides nothing.
    An immediate or session-bound request is actionable only while its source-supported opportunity is still live. If the source explicitly says 'right now', gives a short validity period, or ties the request to a session that later evidence establishes has ended, do not revive that obsolete moment as a current task. Interpret the scope of the requested action: additional usage time for a current session, guarding an occupied doorway, or starting the current meal are moment-bound help, not durable debts. A days-old notification about that moment is insufficient evidence of a current obligation unless later context reaffirms it. Repeated notifications for the same temporary opportunity supersede older requests; they do not accumulate permanent tasks. By contrast, permission to buy or install something, required paperwork, repairs and promised deliverables can remain outstanding across days. Do not invent expiration dates or expire durable work merely because it is old. A current request for permission or approval should be framed as a decision (review/decide whether), never as a command to approve or grant it unless the user has already made that choice. This includes purchase/install approvals: use Decide whether or Review, not Approve, Grant, or Buy.
    Prefer one substantive outcome per obligation over separate navigation steps. Use current task context to avoid recreating a reviewed, completed, dismissed or already represented obligation. Do not suppress genuinely distinct requirements just because they share an activity, sender or organization. Empty tasks is the correct result when no supported outstanding responsibility remains.
    """
}
