#!/usr/bin/env python3
"""Regenerate the shared CSS from checked-in donor token references."""
from pathlib import Path
import re
root = Path(__file__).resolve().parent.parent / 'src/web/projects/maple-common/src/lib/theme'
tokens = (root / 'just-maple-tokens.css').read_text()
light = tokens.split(':root {', 1)[1].split('\n}', 1)[0]
dark = tokens.split("[data-theme='dark'] {", 1)[1].split('\n}', 1)[0]
typography = (root / '_maple-typography-reference.scss').read_text()
on_primary = re.search(r'--color-snow:\s*([^;]+);', light).group(1)
light += '\n--color-on-primary: ' + on_primary + ';'
dark += '\n--color-link: var(--color-text-main);\n--color-writing: var(--color-maple);\n--color-focus: var(--color-text-main);'
type_tokens = '\n'.join(re.findall(r'  --text-[^;]+;', typography))
utility = '\n'.join(re.findall(r'@utility [\w-]+ \{[^}]+\}', typography))
css = '''/* Generated by scripts/generate-ui-theme.py. See docs/UI-PROVENANCE.md. */
@import "tailwindcss";
@import "./fonts.css";
@source "../ui";
@source "../icons";
@source "../../../fesm2022";
@theme {
'''+light+'\n'+type_tokens+'''
--color-primary-dim: var(--color-primary-light);
--color-border-hi: var(--color-text-muted);
--color-success-text: var(--color-status-success-text);
--color-error-text: var(--color-status-error-text);
--color-danger: var(--color-status-error-text);
--color-warn: var(--color-method-put);
--color-link: var(--color-primary);
--color-focus: var(--color-primary);
--color-writing: var(--color-primary);
--color-source: var(--color-info);
--color-agent: var(--color-status-success-text);
--ease-default: cubic-bezier(0.22, 1, 0.36, 1);
}
'''+utility+'''
:root { color-scheme: light; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) {
'''+dark+'\ncolor-scheme: dark;\n} }\n:root[data-theme="dark"], :root.dark {\n'+dark+'\ncolor-scheme: dark;\n}\n'
(root / 'theme.css').write_text(css)
