#!/usr/bin/env python3
"""Regenerate the shared CSS from checked-in donor token references."""
from pathlib import Path
import re
root = Path(__file__).resolve().parent.parent / 'src/web/projects/maple-common/src/lib/theme'
light = (root / 'just-maple-tokens.css').read_text().split(':root {', 1)[1].split('\n}', 1)[0]
dark = re.findall(r'^\$maple-color-([\w-]+): ([^;]+);', (root / '_maple-dark-tokens.scss').read_text(), re.M)
typography = (root / '_maple-typography-reference.scss').read_text()
type_tokens = '\n'.join(re.findall(r'  --text-[^;]+;', typography))
utility = '\n'.join(re.findall(r'@utility [\w-]+ \{[^}]+\}', typography))
css = '''/* Generated by scripts/generate-ui-theme.py. See docs/UI-PROVENANCE.md. */
@import "tailwindcss";
@import "./fonts.css";
@source "../ui";
@source "../icons";
@source "../../../fesm2022";
@theme {
'''+light+'\n'+type_tokens+'''
--color-primary-dim: #f5e6e4;
--color-border-hi: #a8a29e;
--color-success-text: #166534;
--color-error-text: #991b1b;
--ease-default: cubic-bezier(0.22, 1, 0.36, 1);
}
'''+utility+'''
:root { color-scheme: light dark; }
@media (prefers-color-scheme: dark) { :root {
'''+''.join(f'--color-{name}: {value};\n' for name,value in dark)+'} }\n'
(root / 'theme.css').write_text(css)
