import { TestBed } from '@angular/core/testing';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { HistoryComponent, InboxItem, InboxPage } from './history.component';
import { NativeBridge } from '../core/native-bridge.service';
const row=(id:string):InboxItem=>({id,connector:'gmail',sender:'Fixture Person',subject:'Fixture subject',preview:'Short fixture text',status:'processed',statusDetail:'Processed',analysisStatus:'waiting',occurredAt:1800000000,tags:[{id:'activity',name:'Fixture activity'}]});
const page=(ids:string[],next=false):InboxPage=>({items:ids.map(row),total:100,nextCursor:next?{eventID:ids.at(-1)!,occurredAt:1800000000,snapshotRowID:100}:null,sources:[{connector:'gmail',name:'Gmail',count:100}]});
function setup(){const historyInbox=vi.fn().mockResolvedValue(page([])),inspectSource=vi.fn();TestBed.configureTestingModule({providers:[{provide:NativeBridge,useValue:{historyInbox,inspectSource}}]});const fixture=TestBed.createComponent(HistoryComponent);return{fixture,c:fixture.componentInstance,historyInbox,inspectSource};}
describe('History inbox',()=>{
 afterEach(()=>TestBed.resetTestingModule());
 it('renders a virtual inbox with bounded DOM and lazy source details',async()=>{const{fixture,c,historyInbox,inspectSource}=setup();historyInbox.mockResolvedValue(page(Array.from({length:1000},(_,i)=>String(i))));fixture.detectChanges();await fixture.whenStable();fixture.detectChanges();expect(c.rows()).toHaveLength(1000);expect(fixture.nativeElement.querySelectorAll('.inbox-row').length).toBeLessThan(50);expect(fixture.nativeElement.textContent).toContain('Fixture Person');expect(fixture.nativeElement.textContent).toContain('Analysis waiting');expect(inspectSource).not.toHaveBeenCalled();});
 it('uses the server cursor once during duplicate scroll requests and preserves loaded rows on failure',async()=>{const{c,historyInbox}=setup();historyInbox.mockResolvedValueOnce(page(['a','b'],true));await c.refresh();let fail!:(e:Error)=>void;historyInbox.mockReturnValueOnce(new Promise((_,reject)=>{fail=reject;}));const more=c.more();void c.more();expect(historyInbox).toHaveBeenCalledTimes(2);expect(historyInbox.mock.calls[1][0].eventID).toBe('b');fail(new Error('Disconnected'));await more;expect(c.rows().map(r=>r.id)).toEqual(['a','b']);expect(c.next()?.eventID).toBe('b');expect(c.error()).toContain('Disconnected');});
 it('resets server pagination when selecting a connector and ignores stale responses',async()=>{const{c,historyInbox}=setup();let resolve!:(p:InboxPage)=>void;historyInbox.mockReturnValueOnce(new Promise(r=>resolve=r));const first=c.refresh();historyInbox.mockResolvedValueOnce(page(['mail']));c.selectConnector('gmail');resolve(page(['stale'],true));await first;await Promise.resolve();expect(historyInbox.mock.calls[1]).toEqual([undefined,'gmail']);expect(c.rows().map(r=>r.id)).toEqual(['mail']);});
 it('keeps source selection stable against out of order loads and closing',async()=>{const{c,inspectSource}=setup();let resolve!:(v:unknown)=>void;inspectSource.mockReturnValueOnce(new Promise(r=>resolve=r));const old=c.inspect('old');inspectSource.mockResolvedValueOnce({id:'new',connector:'gmail',content:'Fixture',truncated:false,available:true});await c.inspect('new');resolve({id:'old'});await old;expect(c.source()?.id).toBe('new');c.closeSource();expect(c.source()).toBeNull();});
});
